import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1779866800083 implements MigrationInterface {
    name = ' $npmConfigName1779866800083'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tbl_01_M_Branch\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Branch_Code\` varchar(255) NOT NULL, \`Branch_Name\` varchar(255) NOT NULL, \`Branch_ShortName\` varchar(255) NOT NULL, \`Org_Code\` varchar(255) NOT NULL, \`Branch_Gst\` varchar(255) NULL, \`State_Code\` varchar(255) NULL, \`City\` varchar(255) NULL, \`Pin\` varchar(255) NULL, \`Location\` varchar(255) NULL, \`Address2\` varchar(255) NULL, \`Address3\` varchar(255) NULL, \`Created_By\` varchar(255) NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Modified_By\` varchar(255) NULL, \`Modified_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`Dflag\` tinyint NOT NULL DEFAULT 0, \`IsMainBranch\` varchar(255) NULL, UNIQUE INDEX \`IDX_581ac6eb987e17f5f9bacd48f6\` (\`Branch_Name\`), PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Tbl_01_M_Expenses_Head\` (\`Head_Id\` int NOT NULL AUTO_INCREMENT, \`Head_Name\` varchar(255) NOT NULL, \`Applicable_For\` varchar(50) NULL, \`Default_Limit\` varchar(50) NULL, \`Fin_Year\` varchar(50) NULL, \`Org_Code\` varchar(50) NULL, \`Created_By\` varchar(50) NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Modified_By\` varchar(50) NOT NULL, \`Modified_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`Dflag\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`IDX_3a5ba7f3167c09251d1e270aa9\` (\`Head_Name\`), PRIMARY KEY (\`Head_Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tbl_01_M_Org\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Org_Code\` varchar(255) NOT NULL, \`Org_Name\` varchar(255) NOT NULL, \`Org_ShortName\` varchar(255) NOT NULL, \`Org_Reg_No\` varchar(255) NULL, \`Org_Gst\` varchar(255) NULL, \`TAN_No\` varchar(255) NULL, \`Org_Pan\` varchar(255) NULL, \`Org_Gstin_No\` varchar(255) NULL, \`Org_FinancialYear\` datetime NULL, \`Org_EnableTDSDeduction\` varchar(255) NULL, \`Org_TDSDeductionType\` varchar(255) NULL, \`Org_Distritct_No\` varchar(255) NULL, \`Org_City\` varchar(255) NULL, \`Org_State_Code\` varchar(255) NULL, \`Org_Pin\` varchar(255) NULL, \`Org_Phone\` varchar(255) NULL, \`Org_Email\` varchar(255) NULL, \`Org_Registered_Address\` varchar(255) NULL, \`DocumentType\` varchar(255) NULL, \`Document\` varchar(255) NULL, \`Org_Charter_Date\` datetime NULL, \`Org_Location\` varchar(255) NULL, \`Org_Logo\` varchar(255) NULL, \`Enable_TDS_Deduction\` varchar(255) NULL, \`Deductor_Type\` varchar(255) NULL, \`Address\` varchar(255) NOT NULL, \`ContactNo1\` varchar(255) NULL, \`FaxNo\` varchar(255) NULL, \`Email1\` varchar(255) NULL, \`website\` varchar(255) NULL, \`ServiceTax\` varchar(255) NULL, \`TanNo\` varchar(255) NULL, \`Dept_Logo\` varchar(255) NULL, \`Cash_Acnt_No\` varchar(255) NULL, \`Tin_No\` varchar(255) NULL, \`Dflag\` int NOT NULL DEFAULT 0, \`Created_By\` varchar(255) NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Modified_By\` varchar(255) NULL, \`Modified_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_7cf176bab20e9195793b0e2975\` (\`Org_Code\`), UNIQUE INDEX \`IDX_6bd5e2580de99ed65e3ed01080\` (\`Org_Name\`), PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Tbl_01_M_Opening_Balance\` (\`OB_Id\` int NOT NULL AUTO_INCREMENT, \`OB_Date\` datetime NULL, \`OB_Amount\` decimal(18,2) NULL, \`Closing_Balance\` decimal(18,2) NULL, \`Remarks\` varchar(100) NULL, \`Org_Code\` varchar(50) NULL, \`Created_By\` varchar(50) NULL, \`Created_Date\` datetime NULL, \`Modified_By\` varchar(50) NULL, \`Modified_Date\` datetime NULL, \`Dflag\` int NOT NULL DEFAULT '0', \`Fin_Year\` varchar(50) NULL, PRIMARY KEY (\`OB_Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tbl_01_M_P_Page\` (\`PG_Id\` int NOT NULL AUTO_INCREMENT, \`MG_Id\` int NOT NULL, \`M_Id\` int NOT NULL, \`PG_Name\` varchar(255) NOT NULL, \`Controller_Name\` varchar(255) NOT NULL, \`Action_Name\` varchar(255) NOT NULL, \`Page_Menu_Icon\` varchar(255) NOT NULL, \`Ord_Seq\` int NOT NULL, \`Dflag\` int NOT NULL, \`Created_By\` varchar(255) NOT NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Modified_By\` varchar(255) NULL, \`Modified_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`PG_Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tbl_01_M_P_Module\` (\`MG_Id\` int NOT NULL AUTO_INCREMENT, \`M_Id\` int NOT NULL, \`M_Name\` varchar(200) NOT NULL, \`M_Icon\` varchar(200) NULL, \`M_Order\` int NULL, \`Dflag\` tinyint NULL DEFAULT 0, \`Created_By\` varchar(50) NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`MG_Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Peety_Cash_All_Transaction\` (\`Tran_Id\` int NOT NULL AUTO_INCREMENT, \`Tran_No\` varchar(50) NULL, \`Tran_Date\` datetime NULL, \`Voucher_No\` varchar(50) NULL, \`Tran_Desc\` varchar(50) NULL, \`In_Amount\` decimal(18,2) NULL, \`Out_Amount\` decimal(18,2) NULL, \`Created_By\` varchar(50) NULL, \`Created_Date\` datetime NULL, \`Modified_By\` varchar(50) NULL, \`Modified_Date\` datetime NULL, \`Dflag\` int NOT NULL DEFAULT '0', \`Org_Code\` varchar(50) NULL, \`Fin_Year\` varchar(50) NULL, PRIMARY KEY (\`Tran_Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tbl_01_M_P_Role\` (\`Role_Id\` int NOT NULL AUTO_INCREMENT, \`Role_Name\` varchar(50) NULL, \`Org_Code\` varchar(255) NULL, \`Dflag\` tinyint NULL DEFAULT 0, \`Created_By\` varchar(50) NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Modified_By\` varchar(50) NULL, \`Modified_Date\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`Role_Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tbl_01_M_P_RoleAccess\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`Role_Id\` int NOT NULL, \`M_Id\` int NOT NULL, \`PG_Id\` int NOT NULL, \`READ\` int NOT NULL, \`WRITE\` int NOT NULL, \`UPDATE\` int NOT NULL, \`DELETE\` int NOT NULL, \`Org_Code\` varchar(255) NOT NULL, \`Dflag\` int NOT NULL, \`Created_By\` varchar(255) NOT NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Modified_By\` varchar(255) NULL, \`Modified_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tTbl_01_M_Route\` (\`Route_Id\` int NOT NULL AUTO_INCREMENT, \`Route_Name\` varchar(255) NOT NULL, \`Route_From\` varchar(255) NOT NULL, \`Route_To\` varchar(255) NOT NULL, \`Route_Distance\` int NOT NULL, \`Route_Code\` varchar(50) NOT NULL, \`Route_No\` varchar(255) NOT NULL, \`Fin_Year\` varchar(255) NULL, \`Org_Code\` varchar(255) NULL, \`Created_By\` varchar(255) NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Modified_By\` varchar(255) NULL, \`Modified_Date\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`Dflag\` int NULL DEFAULT 0, PRIMARY KEY (\`Route_Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tbl_01_M_P_User\` (\`userId\` int NOT NULL AUTO_INCREMENT, \`userCode\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`fullName\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`status\` enum ('Active', 'InActive') NOT NULL DEFAULT 'Active', \`orgCode\` varchar(255) NOT NULL, \`branchCode\` varchar(255) NOT NULL, \`mobile\` varchar(255) NULL, \`email\` varchar(255) NULL, \`createdBy\` varchar(255) NULL, \`createDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`modifiedBy\` varchar(255) NULL, \`modifiedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`dflag\` tinyint NOT NULL DEFAULT 0, \`roleId\` int NULL, UNIQUE INDEX \`IDX_8668312df2f2c553f41029e45e\` (\`userCode\`), UNIQUE INDEX \`IDX_d4f78fbcdf9eb8f79c72cfbbe2\` (\`name\`), PRIMARY KEY (\`userId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tbl_01_M_P_UserAccess\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`User_Code\` varchar(255) NOT NULL, \`Role_Id\` int NOT NULL, \`M_Id\` int NOT NULL, \`PG_Id\` int NOT NULL, \`READ\` int NOT NULL, \`WRITE\` int NOT NULL, \`UPDATE\` int NOT NULL, \`DELETE\` int NOT NULL, \`Org_Code\` varchar(255) NOT NULL, \`Dflag\` int NOT NULL, \`Created_By\` varchar(255) NOT NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Modified_By\` varchar(255) NULL, \`Modified_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Tbl_01_M_Vehicle\` (\`Vehicle_Id\` int NOT NULL AUTO_INCREMENT, \`Vehicle_No\` varchar(50) NULL, \`Vehicle_Type\` varchar(50) NOT NULL, \`V_Model\` varchar(50) NULL, \`Vehicle_OwnerName\` varchar(50) NOT NULL, \`Vehicle_Capacity\` varchar(50) NOT NULL, \`Case_Approx\` int NOT NULL, \`Fin_Year\` varchar(50) NULL, \`Org_Code\` varchar(50) NOT NULL, \`Created_By\` varchar(50) NOT NULL, \`Created_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`Modified_By\` varchar(50) NULL, \`Modified_Date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`Dflag\` int NULL DEFAULT 0, PRIMARY KEY (\`Vehicle_Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Tbl_01_V_Master\` (\`Id\` int NOT NULL AUTO_INCREMENT, \`V_Name\` varchar(100) NOT NULL, PRIMARY KEY (\`Id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`tbl_token\` ADD CONSTRAINT \`FK_7d303a5f7214453fb74580d1dcc\` FOREIGN KEY (\`userId\`) REFERENCES \`tbl_01_M_P_User\`(\`userId\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`tbl_token\` DROP FOREIGN KEY \`FK_7d303a5f7214453fb74580d1dcc\``);
        await queryRunner.query(`DROP TABLE \`Tbl_01_V_Master\``);
        await queryRunner.query(`DROP TABLE \`Tbl_01_M_Vehicle\``);
        await queryRunner.query(`DROP TABLE \`tbl_01_M_P_UserAccess\``);
        await queryRunner.query(`DROP INDEX \`IDX_d4f78fbcdf9eb8f79c72cfbbe2\` ON \`tbl_01_M_P_User\``);
        await queryRunner.query(`DROP INDEX \`IDX_8668312df2f2c553f41029e45e\` ON \`tbl_01_M_P_User\``);
        await queryRunner.query(`DROP TABLE \`tbl_01_M_P_User\``);
        await queryRunner.query(`DROP TABLE \`tTbl_01_M_Route\``);
        await queryRunner.query(`DROP TABLE \`tbl_01_M_P_RoleAccess\``);
        await queryRunner.query(`DROP TABLE \`tbl_01_M_P_Role\``);
        await queryRunner.query(`DROP TABLE \`Peety_Cash_All_Transaction\``);
        await queryRunner.query(`DROP TABLE \`tbl_01_M_P_Module\``);
        await queryRunner.query(`DROP TABLE \`tbl_01_M_P_Page\``);
        await queryRunner.query(`DROP TABLE \`Tbl_01_M_Opening_Balance\``);
        await queryRunner.query(`DROP INDEX \`IDX_6bd5e2580de99ed65e3ed01080\` ON \`tbl_01_M_Org\``);
        await queryRunner.query(`DROP INDEX \`IDX_7cf176bab20e9195793b0e2975\` ON \`tbl_01_M_Org\``);
        await queryRunner.query(`DROP TABLE \`tbl_01_M_Org\``);
        await queryRunner.query(`DROP INDEX \`IDX_3a5ba7f3167c09251d1e270aa9\` ON \`Tbl_01_M_Expenses_Head\``);
        await queryRunner.query(`DROP TABLE \`Tbl_01_M_Expenses_Head\``);
        await queryRunner.query(`DROP INDEX \`IDX_581ac6eb987e17f5f9bacd48f6\` ON \`tbl_01_M_Branch\``);
        await queryRunner.query(`DROP TABLE \`tbl_01_M_Branch\``);
    }

}
